use XrtGraph;

$config = XrtGraph::new_config();
XrtGraph::xrt3d_info_filename_set($config,"output.xwd");
XrtGraph::xrt3d_info_argc_set($config,1);
XrtGraph::xrt3d_info_argv_set($config,["perl_graph"]);
XrtGraph::xrt3d_info_x_min_set($config,0);
XrtGraph::xrt3d_info_y_min_set($config,0);
XrtGraph::xrt3d_info_x_step_set($config,1);
XrtGraph::xrt3d_info_y_step_set($config,1);
XrtGraph::xrt3d_info_x_cnt_set($config,3);
XrtGraph::xrt3d_info_y_cnt_set($config,3);
XrtGraph::xrt3d_info_data_set($config,[[1, 2, 3],[2, 3, 4],[3, 4, 5]]);
XrtGraph::xrt3d_info_header_set($config,["Header line 1", "Line 2!"]);
XrtGraph::xrt3d_info_footer_set($config,["Footer line 1", "Line 2!"]);
XrtGraph::xrt3d_info_x_title_set($config,"x-title");
XrtGraph::xrt3d_info_y_title_set($config,"y-title");
XrtGraph::xrt3d_info_z_title_set($config,"z-title");
XrtGraph::xrt3d_info_x_labels_set($config,["a", "b", "c"]);
XrtGraph::xrt3d_info_y_labels_set($config,["x", "y", "z"]);
XrtGraph::graph_xrt3d($config);
XrtGraph::delete_config($config);
